Update release workflow with package registry automation

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,6 +3,10 @@ on:
   release:
     types: [published]
 
+env:
+  package_name: Token Action HUD DS4
+  package_id: token-action-hud-ds4
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -31,7 +35,7 @@ jobs:
       # Run build
       - uses: actions/setup-node@v3
         with:
-          node-version: "18"
+          node-version: "22"
       - run: npm install
       - run: npm run build
 
@@ -54,9 +58,40 @@ jobs:
           tag: ${{ github.event.release.tag_name }}
           body: ${{ github.event.release.body }}
 
-      # Push the update to the FoundryVTT package registry
-      - name: Release FoundryVTT Package
-        uses: illandril/FoundryVTT-package-release-action@v1.0.2
-        with:
-          package-release-token: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
-          manifest-url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json"
+      - name: Get Compatibility
+        if: "!github.event.release.prerelease"
+        run: |
+          echo 'COMPATIBILITY<<EOF' >> $GITHUB_ENV
+          cat module.json | jq .compatibility >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+
+      - name: Send package to FoundryVTT registry
+        if: "!github.event.release.prerelease"
+        run: |
+          HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X POST 'https://api.foundryvtt.com/_api/packages/release_version/' \
+          --header 'Authorization: ${{ secrets.PACKAGE_RELEASE_TOKEN }}' \
+          --header 'Content-Type: application/json' \
+          --data '{
+              "id": "${{env.package_id}}",
+              "release": {
+                  "version": "${{ github.event.release.tag_name }}",
+                  "manifest": "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json",
+                  "notes": "https://github.com/${{github.repository}}/releases/tag/${{github.event.release.tag_name}}",
+                  "compatibility": ${{ env.COMPATIBILITY }}
+              }
+          }')
+
+          # extract the body
+          HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+
+          # extract the status
+          HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+
+          # print the body
+          echo "$HTTP_BODY"
+
+          # example using the status
+          if [ ! $HTTP_STATUS -eq 200  ]; then
+            echo "Error [HTTP status: $HTTP_STATUS]"
+            exit 1
+          fi
